### ISSUE TITLE
Bad Request (HTTP 400)

### ISSUE THREAD

**Issue by c-scholz-acribit** [smalot/cups-ipp#7]
I am using the library inside a Laravel 5.6 application.

When I try to print a document I get an exception (HTTP-Statuscode 400 - "Bad Request").

```
$client = new Client('scholz', '123456');
$builder = new Builder();
$responseParser = new ResponseParser();

$printerManager = new PrinterManager($builder, $client, $responseParser);
$printer = $printerManager->findByUri('ipp://localhost:631/printers/inpas');

$jobManager = new JobManager($builder, $client, $responseParser);

$job = new Job();
$job->setName($printjob->title);
$job->setUsername('scholz');
$job->addFile('./storage/app/'.$printjob->file);
$job->addAttribute('media', $printjob->format);
$job->addAttribute('orientation-requested', $printjob->orientation);
$job->addAttribute('fit-to-page', true);
$job->setPageRanges($printjob->range);

$result = $jobManager->send($printer, $job);

```
Check a screenshot of the Exception here:
https://www2.pic-upload.de/img/35784064/Bildschirmfotovom2018-08-1316-47-35.png

Any ideas what I could try? The provided data in the $printjob Object is correct, too, because I fixed any errors with this by now. Also I added www-data user (Apache) to lp usergroup in Ubuntu. 

I am just wondering how I'd maybe get around this 400 error and finally print a pdf...

**Comment by c-scholz-acribit** [comment]
Okay I came to the conclusion that actually some provided values were wrong or I called them wrongly. Here's what I found out or need help with @smalot 

- setCopies() can not be omitted and param cannot be null
- setPageRanges() can not be omitted and param cannot be in the allowed format for lp printing "-n, n, n-m, n-" but only in format "n-m, n"
- I couldn't get the "orientation-requested" attribute to work, maybe I am confused but printer says: 
`"orientation-requested-supported" => [ 0=>"portrait", 1=>"landscape", 2=>"reverse-landscape", 3=>"reverse-portrait"]` and I tried all combinations: " `$job->addAttribute('orientation-requested', 'landscape');` , `$job->addAttribute('orientation-requested', 1)`, `$job->addAttribute('orientation-requested', 1)` 
also with value 4 (like it's stated in the CUPS documentation) and the setAttribute()-method, yet the request keeps returning a 400 HTTP error
- how do I set options I find with `lpoptions -d [printername]` ? like "Collate", "ColorModel", "PageSize", "InputSource" etc.

**Comment by c-scholz-acribit** [comment]
Duplicate of https://github.com/smalot/cups-ipp/issues/2

**Comment by c-scholz-acribit** [comment]
Duplicate of https://github.com/smalot/cups-ipp/issues/2

**Comment by chriskonnertz** [comment]
It might also be worth a note, that there is no straight way to print "all" pages of a document. `setPageRanges()` cannot be ommitted,so we have to specify a range. One solution is to use something like `setPageRanges('1-99')' - just set the max range value to a high value that you hopefully will never exceed.
